name: build-executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install mingw-w64
      run: sudo apt-get install -y mingw-w64
    - name: make
      run: make
