on:
  push:
    tags:
    - '*'

jobs:
  build:
    steps:
    - uses: actions/checkout@v4
    - name: install mingw-w64
      run: sudo apt-get install -y mingw-w64
    - name: make
      run: make
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.exe"