name: build-executable

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: install requriements
      run: pip install -r requirements.txt
    - name: run pyinstaller
      run: pyinstaller -F main.py
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*.exe"
