on:
  push:
    tags:
    - '*'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install mingw-w64
      run: sudo apt-get install -y mingw-w64
    - name: give script executable rights
      run: sudo chmod +x ./utils/write-scripts-into-constants.sh
    - name: make
      run: make
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.exe"